In [3]:
import pandas as pd

df = pd.read_csv('Lligues europees UEFA.csv', index_col=0, encoding='latin-1', sep=';')
df

,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/G,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
Rk,,,,,,,,,,,,,,,,,,,,
1,Manchester City,ENG,1,37,28,6,3,96,24,72,90,2.43,86.1,26.8,59.3,1.60,W W W W D,52739,Kevin De Bruyne - 15,Ederson
2,Liverpool,ENG,2,36,26,8,2,89,24,65,86,2.39,84.6,33.1,51.4,1.43,W W W D W,53367,Mohamed Salah - 22,Alisson
3,Real Madrid,ESP,1,37,26,7,4,80,31,49,85,2.30,73.0,45.8,27.2,0.73,W W L W D,40624,Karim Benzema - 27,Thibaut Courtois
4,Bayern Munich,GER,1,34,24,5,5,97,37,60,77,2.26,88.1,37.1,51.0,1.50,W W L D D,33176,Robert Lewandowski - 35,Manuel Neuer
5,Paris S-G,FRA,1,37,25,8,4,85,36,49,83,2.24,71.6,38.1,33.4,0.90,W D D D W,41188,Kylian Mbappé - 25,Keylor Navas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Bordeaux,FRA,20,37,5,13,19,48,89,-41,28,0.76,41.3,68.5,-27.2,-0.73,D L L L D,22083,Hwang Ui-jo - 11,Benoît Costil
95,Venezia,ITA,20,37,6,8,23,34,69,-35,26,0.70,35.4,70.5,-35.1,-0.95,L L L W D,6705,Thomas Henry - 9,Sergio Romero
96,Watford,ENG,19,37,6,5,26,33,75,-42,23,0.62,37.8,64.1,-26.3,-0.71,L L L D L,20614,Emmanuel Dennis - 10,Ben Foster
97,Norwich City,ENG,20,37,5,7,25,23,79,-56,22,0.59,33.0,73.3,-40.4,-1.09,L L L L D,26826,Teemu Pukki - 11,Tim Krul
98,Greuther Fürth,GER,18,34,3,9,22,28,82,-54,18,0.53,30.7,60.3,-29.6,-0.87,D L D L L,7672,Branimir Hrgota - 9,Sascha Burchert

In [ ]:
EXERCICI 1

In [6]:
# import packages
import scipy.stats as stats
import pandas as pd
  
# loading the csv file
data = df['xGD']
  
# perform one sample t-test
t_statistic, p_value = stats.ttest_1samp(a=data, popmean=5000)
print(t_statistic , p_value)

-2475.8039840939555 1.1886584497496247e-234

In [ ]:
Interpretación de resultados:
Como p-value es menor de 0.05 podemos rechazar la hipotesis nula.

In [ ]:
EXERCICI 2
H0: media de goles de la los equipos italianos es igual que en el resto de paises
H1: media de goles de la los equipos italianos es diferente que en el resto de paises
    
Before conducting the two-sample T-Test we need to find if the given data groups have the same variance. If the ratio of the larger data groups to the small data group is less than 4:1 then we can consider that the given data groups have equal variance.

In [14]:
# Import library
import scipy.stats as stats
import numpy as np
 
# Creating data groups


data_group1 = df.loc[df['Country']!='ITA', ['GF']]
data_group2 = df.loc[df['Country']=='ITA', ['GF']]
 
# Print the variance of both data groups
print(np.var(data_group1), np.var(data_group2))

GF    266.934254
dtype: float64 GF    212.41
dtype: float64

In [15]:
# two sample T-test
 
# Import the library
import scipy.stats as stats

# Perform the two sample t-test with equal variances
stats.ttest_ind(a=data_group1, b=data_group2, equal_var=True)

Ttest_indResult(statistic=array([-0.56533074]), pvalue=array([0.57316769]))

In [ ]:
Interpretacion de resultados: 
Como el p-value es mayor que alpha=0.05 no podemos rechazar la hipotesis nula. No hay evidencias suficientes para decir que la media de goles de la liga italiana es diferente que la del resto de equipos europeos.

In [ ]:
Exercici 3
Is there a statistically significant difference in the mean weight loss among the four diets
¿Hay diferencia significativa entre la media de goles en contra de las ligas de España, Inglaterra y Alemania?
H0: las medias de todas las ligas son iguales
H1: al menos la media de una de las ligas es diferente de las otras

In [17]:
# ANOVA
# Example of the Analysis of Variance Test
from scipy.stats import f_oneway
ESP = df.loc[df['Country']=='ESP', ['GF']]
ENG = df.loc[df['Country']=='ENG', ['GF']]
GER = df.loc[df['Country']=='GER', ['GF']]
stat, p = f_oneway(ESP, ENG, GER)
print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
	print('Probably the same distribution')
else:
	print('Probably different distributions')

stat=0.704, p=0.499
Probably the same distribution

In [ ]:
Interpretacion de resultados:
Como el p-value es mayor que alpha=0.05 no podemos rechazar la hipotesis nula. No hay evidencias suficientes para decir que la media de goles en contra de una de las ligas es diferente a la de las demas.